### ISSUE TITLE
ampliación CIF

### ISSUE THREAD

**Issue by xmon** [xinjia95/SpainValidatorBundle#1]
Buenos días,

primero muchas gracias por el bundle ;-)

segundo, necesitaba también validación de CIF y de CIF / DNI, he creado las 2 validaciones para un proyecto que estoy desarrollando.

¿como puedo contribuir y enviarlos para que los puedas revisar y si todo OK añadir al bundle?

nota: soy nuevo aquí, por eso la pregunta un tanto absurda.

**Comment by avegao** [comment]
Buenas,

Lo primero que debes hacer es hacer un commit y luego hacer push a tu repositorio (https://github.com/xmon/SpainValidatorBundle) después tienes que hacer una Pull Request (PR) y ya ahí veré los cambios para incluirlos en el repo.

Muchas gracias por tu colaboración
